### PR TITLE
Don't create the logger in each method

### PR DESCRIPTION
**Pull request by mebubo**

### CODE REVIEW

**Comment by mebubo** [comment]
Trying to fix the tests :)

**Comment by mauriciojost** [comment]
@mebubo you're now a contributor of the project.

**Comment by mauriciojost** [comment]
About the script to initialize the DB with some data, here it is: 
https://github.com/mauriciojost/main4ino-server/blob/6d54bbb04a440c4636066b37548479605f19004e/misc/scripts/populate#L1

**Comment by mauriciojost** [comment]
@mebubo you're not waiting from something on my side, are you?

**Pull request closed without merging**
